default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: mmihaylov
  username: 'dev'
  password: 'dev123'

test:
  <<: *default
  database: mmihaylov_test
  username: 'dev'
  password: 'dev123'
